In [3]:
import torch
import torch.nn.functional as F
data = torch.ones(4, 4)
# pad(left, right, top, bottom)
new_data = F.pad(input=data, pad=(2, 1, 1, 1), mode='constant', value=0)
print(new_data)

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 1., 1., 0.],
        [0., 0., 1., 1., 1., 1., 0.],
        [0., 0., 1., 1., 1., 1., 0.],
        [0., 0., 1., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])


In [55]:
import numpy as np
import scipy

In [20]:
# lets assume this are words
# Every input must have three representations 
input1 = np.array([1,0,1,0])
input2 = np.array([0,2,0,2])
input3 = np.array([1,1,1,1])

In [34]:
# every input have 3 representation (key,query,value)

key_w = np.array([[0, 0, 1],
 [1, 1, 0],
 [0, 1, 0],
 [1, 1, 0]])
query_w = np.array([[1, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 1]])
value_w = np.array([[0, 2, 0],
 [0, 3, 0],
 [1, 0, 3],
 [1, 1, 0]])

In [35]:
# Derive key, query and value

print(input1.shape, key_w.shape)


(4,) (4, 3)


In [36]:
inputs = np.array([input1,input2,input3])

In [37]:
print(inputs)

[[1 0 1 0]
 [0 2 0 2]
 [1 1 1 1]]


In [44]:
# In practice, a bias vector may be added to the product of matrix multiplication.
input_key = inputs.dot(key_w)
input_query = inputs.dot(query_w)
input_value = inputs.dot(value_w)

# query (red) ,keys (orange), value (blue)

In [68]:
input_value

array([[1, 2, 3],
       [2, 8, 0],
       [2, 6, 3]])

In [ ]:
"""To obtain attention scores, we start off with taking a dot product between Input 1’s query (red) 
   with all keys (orange), including itself.
   
   becarefull when you compute the dot product of the matrices
"""

In [53]:
dot_output = input_query[0].dot(input_key.T)

In [57]:
softmax = lambda x:np.exp(x - np.max(x)) / np.exp(x - np.max(x)).sum()

In [58]:
output = softmax(dot_output)

In [61]:
print(output)
print(dot_output)

[0.06337894 0.46831053 0.46831053]
[2 4 4]


In [82]:
final_output = []
for i,val in enumerate(output):
    final_output.append(list(val*input_value[i]))

In [83]:
final_output

[[0.06337893833303762, 0.12675787666607524, 0.19013681499911286],
 [0.9366210616669624, 3.7464842466678494, 0.0],
 [0.9366210616669624, 2.809863185000887, 1.4049315925004435]]

In [100]:
weighted_sum = np.sum(final_output,axis=0)

In [102]:
#  query representation from Input 1
weighted_sum

array([1.93662106, 6.68310531, 1.59506841])